//this is an auto-generated bug report
//package name: com.michaldabski.filemanager
//version: 0.5
//appro_time: 112
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.NullPointerException
 	at com.michaldabski.filemanager.clipboard.Clipboard.pasteFile(Clipboard.java:107)
 	at com.michaldabski.filemanager.clipboard.Clipboard.paste(Clipboard.java:143)
 	at com.michaldabski.filemanager.folders.FolderFragment$4.doInBackground(FolderFragment.java:478)
 	at com.michaldabski.filemanager.folders.FolderFragment$4.doInBackground(FolderFragment.java:448)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
