//this is an auto-generated bug report
//package name: in.shick.diode
//version: 1.2.0
//appro_time: 172
 java.lang.RuntimeException: Unable to resume activity {in.shick.diode/in.shick.diode.filters.FilterListActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2790)
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
 	at in.shick.diode.settings.b.a(RedditSettings.java:500)
 	at in.shick.diode.settings.b.b(RedditSettings.java:272)
 	at in.shick.diode.filters.FilterListActivity.onResume(FilterListActivity.java:71)
 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
 	at android.app.Activity.performResume(Activity.java:5211)
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2780)
