//this is an auto-generated bug report
//package name: org.nv95.openmanga
//version: 3.0
//appro_time: 176
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.NullPointerException
 	at org.nv95.openmanga.utils.MangaStore.pushPage(MangaStore.java:113)
 	at org.nv95.openmanga.services.DownloadService$DownloadTask.doInBackground(DownloadService.java:243)
 	at org.nv95.openmanga.services.DownloadService$DownloadTask.doInBackground(DownloadService.java:156)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
