java.io.IOException: Error running exec(). Command: [su] Working Directory: null Environment: null
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.lang.ProcessManager.exec(ProcessManager.java:211)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.lang.Runtime.exec(Runtime.java:174)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.lang.Runtime.exec(Runtime.java:247)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.lang.Runtime.exec(Runtime.java:190)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at com.stericson.RootShell.execution.Shell.<init>(Shell.java:144)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:848)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:834)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:826)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at com.stericson.RootShell.RootShell.isAccessGiven(RootShell.java:372)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:616)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at com.dnielfe.manager.dialogs.DirectoryInfoDialog$PartitionInfoTask.doInBackground(DirectoryInfoDialog.java:100)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at com.dnielfe.manager.dialogs.DirectoryInfoDialog$PartitionInfoTask.doInBackground(DirectoryInfoDialog.java:81)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ Caused by: java.io.IOException: Permission denied
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.lang.ProcessManager.exec(Native Method)
09-15 15:05:24.890    3260-3287/com.dnielfe.manager.debug W/System.err﹕ at java.lang.ProcessManager.exec(ProcessManager.java:209)