E/AndroidRuntime(  742): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(  742):        at android.os.AsyncTask$3.done(AsyncTask.java:200)
E/AndroidRuntime(  742):        at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime(  742):        at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime(  742):        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime(  742):        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime(  742):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
E/AndroidRuntime(  742):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
E/AndroidRuntime(  742):        at java.lang.Thread.run(Thread.java:1096)
E/AndroidRuntime(  742): Caused by: java.lang.NullPointerException
E/AndroidRuntime(  742):        at net.somethingdreadful.MAL.PrefManager.<init>(PrefManager.java:17)
E/AndroidRuntime(  742):        at net.somethingdreadful.MAL.api.MALApi.<init>(MALApi.java:44)
E/AndroidRuntime(  742):        at net.somethingdreadful.MAL.MALManager.<init>(MALManager.java:45)
E/AndroidRuntime(  742):        at net.somethingdreadful.MAL.ItemGridFragment$getMangaRecordsTask.doInBackground(ItemGridFragment.java:255)
E/AndroidRuntime(  742):        at net.somethingdreadful.MAL.ItemGridFragment$getMangaRecordsTask.doInBackground(ItemGridFragment.java:1)
E/AndroidRuntime(  742):        at android.os.AsyncTask$2.call(AsyncTask.java:185)
E/AndroidRuntime(  742):        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)