//this is an auto-generated bug report
//package name: ar.rulosoft.mimanganu
//version: 1.60
//appro_time: 123
 android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:863)
 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:235)
 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
 	at ar.rulosoft.mimanganu.componentes.Database.getDatabase(Database.java:116)
 	at ar.rulosoft.mimanganu.componentes.Database.getMangasCondition(Database.java:421)
 	at ar.rulosoft.mimanganu.componentes.Database.getMangas(Database.java:414)
 	at ar.rulosoft.mimanganu.DetailsFragment$1.run(DetailsFragment.java:77)
 	at java.lang.Thread.run(Thread.java:841)
